export const cfg = {
  role: process.env.AGENT_ROLE || "supervisor",
  strategy: process.env.STRATEGY || "general",
  natsUrl: process.env.NATS_URL || "nats://nats:4222",
  qdrantUrl: process.env.QDRANT_URL || "http://qdrant:6333",
  qdrantCollection: process.env.QDRANT_COLLECTION || "crypto_agent_memory",
  openaiModel: process.env.OPENAI_MODEL || "gpt-5.6-sol",
  minEventScore: Number(process.env.MIN_EVENT_SCORE || 60),
  minProposalScore: Number(process.env.MIN_PROPOSAL_SCORE || 72),
  minAClassProbability: Number(process.env.MIN_A_CLASS_PROBABILITY || 0.85),
  symbols: (process.env.SPOT_SYMBOLS || "btcusdt,ethusdt,solusdt,bnbusdt,xrpusdt").split(",").map(s => s.trim().toLowerCase()).filter(Boolean),
  executionMode: process.env.EXECUTION_MODE || "paper",
  maxOrderQuote: Number(process.env.MAX_ORDER_QUOTE || 100),
  maxOpenPositions: Number(process.env.MAX_OPEN_POSITIONS || 3),
  binanceBaseUrl: process.env.BINANCE_BASE_URL || "https://api.binance.com",
  binanceWs: process.env.BINANCE_WS_BASE || "wss://stream.binance.com:9443/stream",
  binanceApiKey: process.env.BINANCE_API_KEY || "",
  binanceApiSecret: process.env.BINANCE_API_SECRET || "",
  xBearerToken: process.env.X_BEARER_TOKEN || "",
  arkhamWebhookSecret: process.env.ARKHAM_WEBHOOK_SECRET || "",
  httpPort: Number(process.env.AGENT_HTTP_PORT || 8787),
};
